AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName : paymenthubmonitor,
      Runtime: python3.9
      Role: arn:aws:iam::608561752920:role/paymenthubrole
      Handler: PaymentHubMonitor_handler
      Code:
        S3Bucket: s3://paymenthubchecker
        S3Key: PaymentHubMonitoring.zip
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active